### ISSUE TITLE
Erro Tema Porto

### ISSUE THREAD

**Issue by henriquemnr** [gamuzatech/gamuza_itaushopline-magento#22]
Estou tendo o erro abaixo no tema porto, pode me ajudar?

:5:{i:0;s:212:"Invalid method Smartwave_Porto_Block_Html_Head::appendItem(Array
(
    [0] => skin_css
    [1] => css/gamuza/itaushopline/itaushopline.css
    [2] => Mage_Core_Model_Layout_Element Object
        (
        )

)
)";i:1;s:2672:"#0 [internal function]: Varien_Object->__call('appendItem', Array)
#1 [internal function]: Smartwave_Porto_Block_Html_Head->appendItem('skin_css', 'css/gamuza/itau...', Object(Mage_Core_Model_Layout_Element))
#2 /usr/share/henrique/mnr4x4-dev/app/code/local/Smartwave/All/Model/Core/Layout.php(141): call_user_func_array(Array, Array)
#3 /usr/share/henrique/mnr4x4-dev/app/code/local/Smartwave/All/Model/Core/Layout.php(79): Smartwave_All_Model_Core_Layout->_runAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#4 /usr/share/henrique/mnr4x4-dev/app/code/core/Mage/Core/Model/Layout.php(214): Smartwave_All_Model_Core_Layout->_generateAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /usr/share/henrique/mnr4x4-dev/app/code/local/Smartwave/All/Model/Core/Layout.php(31): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))

**Comment by irineujunior** [comment]
Salve @henriquemnr 
Fica aqui a solução para futuras consultas =)
Quando for copiar o `app/design/frontend/smartwave/seu-tema-maroto/layout/gamuza/itaushopline.xml`, lembre-se de trocar o **method="appendItem"** para **method="addItem"**

Ficará assim:
```
<layout version="0.1.0">
    <default>
        <reference name="head">
            <action method="addItem"><type>skin_css</type><name>css/gamuza/itaushopline/itaushopline.css</name><params /></action>
        </reference>
    </default>
</layout>
```
